#!/bin/sh

export PATH="$SNAP/usr/sbin:$SNAP/usr/bin:$SNAP/sbin:$SNAP/bin:$PATH"

# Logout & disable firewall before remove
# Calling new instance of 'erebrus-service' with argument, because the service is stopped already
erebrus-service --cleanup
